## 12/09/23
Working over linear algebra
numpy is used for mathematical analysis whereas pandas is used as data analysis
numpy has only one data type `numpy arrays`
pandas has only two data types `Series` and `DataFrame`
numpy arrays are two types `Matrices` and `Vectors`

In [1]:
import numpy as np

In [ ]:
li = [1,2,3,4,5,6,7,8]

npar1 = np.array(li,dtype="int8")
print(npar1)
print(type(npar1))
print(npar1.ndim)
print(npar1.dtype)
print(npar1.itemsize,"bytes")
print(npar1.size)
print(len(npar1))
print(npar1.nbytes)

In [24]:
npar1  = np.array([[1,2,7],[3,4,8],[5,6,9]])
print(npar1)
print(type(npar1))
print("Dimension : ",npar1.ndim)

print(npar1.shape)

[[1 2 7]
 [3 4 8]
 [5 6 9]]
<class 'numpy.ndarray'>
Dimension :  2
(3, 3)


In [27]:
npar1  = np.array([[[1,2,7],[3,4,8],[5,6,9]],
                   [[11,22,77],[33,44,88],[55,66,99]],
                   [[111,222,777],[333,444,888],[555,666,999]]
                   ])
print(npar1)
print(type(npar1))
print("Dimension : ",npar1.ndim)
print("Shape : ",npar1.shape)

[[[  1   2   7]
  [  3   4   8]
  [  5   6   9]]

 [[ 11  22  77]
  [ 33  44  88]
  [ 55  66  99]]

 [[111 222 777]
  [333 444 888]
  [555 666 999]]]
<class 'numpy.ndarray'>
Dimension :  3
Shape :  (3, 3, 3)


## 13/09/23

In [3]:
npar1  = np.array([[[[1,2,7],[3,4,8],[5,6,9]]]])
print(npar1)
print(type(npar1))
print("Dimension : ",npar1.ndim)
print("Shape : ",npar1.shape)

[[[[1 2 7]
   [3 4 8]
   [5 6 9]]]]
<class 'numpy.ndarray'>
Dimension :  4
Shape :  (1, 1, 3, 3)


In [14]:
npar1 = np.arange(10)
print(npar1)
npar1 = np.arange(1,16)
print(npar1)
npar1 = np.zeros((5,3),dtype="int8")
print(npar1)
npar1 = np.zeros((5,3,2),dtype="int8")
print("\n",npar1)


[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

 [[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

 [[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


In [16]:
npar1 = np.zeros((5,3,2,5),dtype="int8")
print(npar1)

[[[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]]]]


In [19]:
npar1 = np.ones(5,dtype="int8")
print(npar1)
npar1 = np.ones((5,3),dtype="int8")
print(npar1)
npar1 = np.ones((5,3,2),dtype="int8")
print(npar1)

[1 1 1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [22]:
npar1 = np.linspace(1,10,100,dtype="int8")
npar1

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10],
      dtype=int8)

In [27]:
npar1 = np.eye(5,5,dtype="int8")
npar1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [30]:
npar1 = np.identity(5,dtype="int8")
npar1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [35]:
npar1 = np.random.rand(2,2)
npar1

array([[0.56473222, 0.63915329],
       [0.43085903, 0.74000073]])

In [36]:
npar1 = np.random.randn(2,2)
npar1

array([[-0.86363282, -2.04731615],
       [-0.43314162,  0.78792522]])

In [38]:
npar1 = np.random.randint(1,10,(2,4))
npar1

array([[1, 3, 4, 2],
       [2, 4, 3, 9]])

In [52]:
npar1 = np.random.randint(500,1000,(2,3,4,6))
npar1 = np.array(npar1,dtype="float64")
print(npar1)
print(type(npar1))
print(npar1.ndim)
print(npar1.dtype)
print(npar1.itemsize,"bytes")
print(npar1.size)
print(len(npar1))
print(npar1.nbytes)

[[[[990. 731. 646. 691. 853. 509.]
   [947. 689. 726. 684. 754. 547.]
   [721. 784. 787. 530. 581. 587.]
   [586. 513. 696. 942. 927. 887.]]

  [[794. 702. 997. 866. 790. 794.]
   [783. 569. 620. 609. 721. 706.]
   [519. 957. 891. 594. 583. 904.]
   [823. 882. 608. 820. 552. 876.]]

  [[597. 575. 858. 959. 947. 955.]
   [566. 670. 864. 936. 765. 745.]
   [691. 881. 702. 920. 983. 966.]
   [947. 733. 867. 563. 624. 713.]]]


 [[[732. 581. 980. 890. 808. 706.]
   [889. 803. 593. 620. 638. 960.]
   [690. 556. 621. 626. 952. 531.]
   [768. 954. 804. 531. 646. 937.]]

  [[892. 542. 880. 744. 937. 967.]
   [856. 609. 906. 958. 578. 661.]
   [756. 667. 635. 893. 561. 716.]
   [812. 596. 892. 911. 977. 784.]]

  [[959. 761. 972. 990. 702. 836.]
   [838. 571. 711. 607. 888. 561.]
   [941. 719. 804. 789. 680. 891.]
   [961. 821. 748. 634. 940. 586.]]]]
<class 'numpy.ndarray'>
4
float64
8 bytes
144
2
1152


In [54]:
npar1 = np.arange(1,241).reshape((2,4,5,6))
npar1

array([[[[  1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36],
         [ 37,  38,  39,  40,  41,  42],
         [ 43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66],
         [ 67,  68,  69,  70,  71,  72],
         [ 73,  74,  75,  76,  77,  78],
         [ 79,  80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96],
         [ 97,  98,  99, 100, 101, 102],
         [103, 104, 105, 106, 107, 108],
         [109, 110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119, 120]]],


       [[[121, 122, 123, 124, 125, 126],
         [127, 128, 129, 130, 131, 132],
         [133, 134, 135, 136, 137, 138],
         [139, 140, 141, 142, 143, 144],
      

In [57]:
npar1 = np.arange(1,721).reshape((4,3,4,5,3))
npar1

array([[[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9],
          [ 10,  11,  12],
          [ 13,  14,  15]],

         [[ 16,  17,  18],
          [ 19,  20,  21],
          [ 22,  23,  24],
          [ 25,  26,  27],
          [ 28,  29,  30]],

         [[ 31,  32,  33],
          [ 34,  35,  36],
          [ 37,  38,  39],
          [ 40,  41,  42],
          [ 43,  44,  45]],

         [[ 46,  47,  48],
          [ 49,  50,  51],
          [ 52,  53,  54],
          [ 55,  56,  57],
          [ 58,  59,  60]]],


        [[[ 61,  62,  63],
          [ 64,  65,  66],
          [ 67,  68,  69],
          [ 70,  71,  72],
          [ 73,  74,  75]],

         [[ 76,  77,  78],
          [ 79,  80,  81],
          [ 82,  83,  84],
          [ 85,  86,  87],
          [ 88,  89,  90]],

         [[ 91,  92,  93],
          [ 94,  95,  96],
          [ 97,  98,  99],
          [100, 101, 102],
          [103, 104, 105]],

         [[106, 107, 108],
          [1

In [60]:
npar1 = np.arange(1,721).reshape((4,3,4,5,-1))
npar1

array([[[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9],
          [ 10,  11,  12],
          [ 13,  14,  15]],

         [[ 16,  17,  18],
          [ 19,  20,  21],
          [ 22,  23,  24],
          [ 25,  26,  27],
          [ 28,  29,  30]],

         [[ 31,  32,  33],
          [ 34,  35,  36],
          [ 37,  38,  39],
          [ 40,  41,  42],
          [ 43,  44,  45]],

         [[ 46,  47,  48],
          [ 49,  50,  51],
          [ 52,  53,  54],
          [ 55,  56,  57],
          [ 58,  59,  60]]],


        [[[ 61,  62,  63],
          [ 64,  65,  66],
          [ 67,  68,  69],
          [ 70,  71,  72],
          [ 73,  74,  75]],

         [[ 76,  77,  78],
          [ 79,  80,  81],
          [ 82,  83,  84],
          [ 85,  86,  87],
          [ 88,  89,  90]],

         [[ 91,  92,  93],
          [ 94,  95,  96],
          [ 97,  98,  99],
          [100, 101, 102],
          [103, 104, 105]],

         [[106, 107, 108],
          [1

In [63]:
npar1 = np.random.randint(1,10,(10))
print(npar1)
npar1.max()

7

In [71]:
npar1 = np.random.randint(1,10,(10))
print(npar1)
npar1.min()

[8 6 4 7 5 9 6 2 7 3]


2

In [72]:
npar1 = np.random.randint(1,10,(10))
print(npar1)
npar1.argmax()

[3 6 5 7 7 1 5 8 2 5]


7

In [78]:
npar1 = np.random.randint(1,10,(5,10))
print(npar1)
npar1.argmax(axis=1)

[[7 2 5 1 2 3 5 8 5 2]
 [2 2 4 3 8 8 2 2 2 2]
 [8 1 9 4 3 2 5 2 2 7]
 [6 9 4 1 5 3 4 8 7 8]
 [2 9 5 5 2 9 9 1 2 8]]


array([7, 4, 2, 1, 1], dtype=int64)

In [76]:
npar1 = np.random.randint(1,10,(5,10))
print(npar1)
npar1.max(axis=1)

[[9 5 7 4 4 1 3 1 6 7]
 [9 9 3 4 9 6 7 4 2 7]
 [2 4 7 3 3 8 9 7 2 5]
 [2 3 2 4 1 6 8 8 3 7]
 [8 8 7 4 7 5 6 9 2 8]]


array([9, 9, 9, 8, 9])

In [89]:
npar1 = np.random.randint(1,50,(5,10))
print(npar1)
npar1.min(axis=1)

[[15 28  4 15 24 22 27  2 39 36]
 [43 48 24 34 20 35  5 20 12 38]
 [49 14  3 45 23 17 17 41  6 11]
 [30  3 17 47 42  8 35 21  6 35]
 [ 5 38 35 18 49 25 46 47 13  6]]


array([2, 5, 3, 3, 5])

In [95]:
myArray = np.array([[45,67,89,45],
                    [67,56,123,54],
                    [112,3,5,7]])
print(myArray)
print(myArray.astype("float"))
myArray

[[ 45  67  89  45]
 [ 67  56 123  54]
 [112   3   5   7]]
[[ 45.  67.  89.  45.]
 [ 67.  56. 123.  54.]
 [112.   3.   5.   7.]]


array([[ 45,  67,  89,  45],
       [ 67,  56, 123,  54],
       [112,   3,   5,   7]])

### 14/09/23

In [13]:
np.random.seed(295)
npar = np.random.randint(500,1000,(15,))
print(npar)

[724 755 871 598 659 792 616 668 547 563 596 971 678 675 944]


In [16]:
npar[:5]

array([724, 755, 871, 598, 659])

In [20]:
'''Brodcasting'''
npar[:5] = 100
npar

array([100, 100, 100, 100, 100, 792, 616, 668, 547, 563, 596, 971, 678,
       675, 944])

In [25]:
np.random.seed(295)
npar = np.random.randint(500,1000,(15))
npar

array([724, 755, 871, 598, 659, 792, 616, 668, 547, 563, 596, 971, 678,
       675, 944])

In [27]:
npar1  = npar[:2]
print(npar1)
npar1 = npar[-2:]
print(npar1)
npar1 = npar[len(npar)//2]
print(npar1)

[724 755]
[675 944]
668


In [34]:
npar1 = np.arange(1,11)
npar1[:5] = [10,11,12,13,14]
npar1

2715668546064
2715668546064


array([10, 11, 12, 13, 14,  6,  7,  8,  9, 10])

In [37]:
npar = npar1.copy()
npar

array([10, 11, 12, 13, 14,  6,  7,  8,  9, 10])

In [69]:
arr = np.array([[5,10,15],
                [20,25,30],
                [35,40,45]
                ])
print(arr[1,1])
print(arr[0:2,1:3])
print(arr[::2,:])
print(arr[:,::2])
print("\n",arr[::2,::2])

25
[[10 15]
 [25 30]]
[[ 5 10 15]
 [35 40 45]]
[[ 5 15]
 [20 30]
 [35 45]]

 [[ 5 15]
 [35 45]]


In [72]:
matrix = np.arange(1,55).reshape(6,9)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [99]:
matrix[[0,1,4]][:,[0,1,-3,-2]]

array([[ 1,  2,  7,  8],
       [10, 11, 16, 17],
       [37, 38, 43, 44]])

In [101]:
matrix[np.ix_([0,1,4],[0,1,-3,-2])]

array([[ 1,  2,  7,  8],
       [10, 11, 16, 17],
       [37, 38, 43, 44]])

In [136]:
setmatrix = np.arange(1,106).reshape(3,5,7)
setmatrix

array([[[  1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19,  20,  21],
        [ 22,  23,  24,  25,  26,  27,  28],
        [ 29,  30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41,  42],
        [ 43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56],
        [ 57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70]],

       [[ 71,  72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89,  90,  91],
        [ 92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105]]])

In [107]:
print(setmatrix[1,[0,-1],::2])

[[36 38 40 42]
 [64 66 68 70]]


In [110]:
arr = np.arange(1,11)
arr>5
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [139]:
setmatrix[np.ix_([2],[0,1,3],[0,1,-3,-2])]

array([[[71, 72, 75, 76],
        [78, 79, 82, 83],
        [92, 93, 96, 97]]])

###  15/09/23
# Arthematic and universal mathematical operations

In [1]:
import numpy as np
arr = np.arange(1,11)

In [2]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
3*arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [6]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [8]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [9]:
np.max(arr)

10

In [11]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [13]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# Splitting

In [15]:
arr = np.arange(1,25).reshape((6,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [17]:
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [21]:
np.vsplit(arr,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

# Joining

In [23]:
combined_rows = np.concatenate(np.vsplit(arr,3))
combined_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [24]:
combined_cols = np.concatenate(np.vsplit(arr,3),axis=1)
combined_cols

array([[ 1,  2,  3,  4,  9, 10, 11, 12, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 13, 14, 15, 16, 21, 22, 23, 24]])